name: Poetry Publish Test

on:
  workflow_dispatch:

  repository_dispatch:
    types: [manual-trigger]
    # TO TEST WORKFLOW MANUALLY:
    # curl -X POST -H "Authorization: token ${GITHUB_TOKEN}" -H "Accept: application/vnd.github.everest-preview+json" "https://api.github.com/repos/mikexilinx/chipscopy-copy/dispatches" -d '{"event_type": "manual-trigger"}'

  push:
    tags:
      - '*'

jobs:
  build:
    name: Build Package
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install Poetry
      run: pip install poetry

    - name: Install dependencies
      run: poetry install

    - name: Build package
      run: poetry build

    - name: Upload built package
      uses: actions/upload-artifact@v2
      with:
        name: built-package
        path: dist/*

  publish-dry-run:
    name: Publish to Test-PyPI
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Download built package
      uses: actions/download-artifact@v2
      with:
        name: built-package
        path: dist

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install Poetry
      run: pip install poetry

    - name: Publish package (Test)
      env:
        TWINE_USERNAME: ${{ secrets.TEST_PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD }}
      run: |
        echo "TWINE_USERNAME length: ${#TWINE_USERNAME}"
        echo "TWINE_PASSWORD length: ${#TWINE_PASSWORD}"
        poetry config repositories.testpypi https://test.pypi.org/legacy/
        poetry config http-basic.testpypi "$TWINE_USERNAME" "$TWINE_PASSWORD"
        poetry publish -r testpypi --username "$TWINE_USERNAME" --password "$TWINE_PASSWORD"
